spring:
  application:
    name: condo-sync
  datasource:
    url: jdbc:mysql://cdm1s48crk8itlnr.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/gtu5j9la4qe2k1u6
    username: kz2kqfyeep87dpcl
    password: mewsngmtannz261v
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 835803190087-v7i0b1ns3g81cmvph0t1l6j4btnvu1vp.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.springframework.security: DEBUG